routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\SiginController;
use App\Http\Controllers\CastController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[IndexController::class,'awal']);

Route::get('/awal',[IndexController::class,'awal']);
Route::get('/form',[IndexController::class,'halaman']);
Route::get('/tabel',[IndexController::class,'tabel']);
Route::post('/home',[SiginController::class,'log']);
Route::resource('/casts', \App\Http\Controllers\CastController::class);

app/Models/Cast.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama', 'umur', 'bio'
    ];
}

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    use HasFactory;
}

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;
}

app/Models/Kritik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kritik extends Model
{
    use HasFactory;
}

app/Models/Peran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Peran extends Model
{
    use HasFactory;
}

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;
use App\Models\Cast;

use Illuminate\Http\Request;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cast = Cast::all();
        return view('casts', compact('cast'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('cast-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate( $request,[
            'nama' => 'required',
            'umur'=> 'required',
            'bio' => 'required'
        ]);

        Cast::create([
            'nama' => $request->nama,
            'umur' => $request->umur,
            'bio' => $request->bio,

        ]);

        return redirect('/casts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $cast = Cast::find($id);

        return view('edit-cast', compact('cast'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            $request->validate([
            'nama' => 'required|unique:Casts,nama',
            'umur' => 'required',
            'bio' => 'required',
        ]);

        $cast = Cast::find($id);
        $cast->nama = $request->nama;
        $cast->umur = $request->umur;
        $cast->bio = $request->bio;
        $cast->update();

        return redirect('/casts');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cast = Cast::find($id);
        $cast->delete();
        return redirect('/casts');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function halaman(){
        return view('form');
    }
    
    public function awal() {
        return view ('depan');
    }

    public function tabel() {
        return view ('tabel');
    }

}

app/Http/Controllers/SiginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiginController extends Controller
{
    public function log (Request $request) {
        $namadepan = $request['namadepan'];
        $namabelakang = $request['namabelakang'];
        
        return view('home', ['namadepan' => $namadepan, 'namabelakang'=> $namabelakang] );
    }
}

resources/views/cast-create.blade.php
@extends('template.layout')

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="content-header">
                <div class="container-fluid">

                    <div class="card">
                        <form action="/casts" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="nama">Nama </label>
                                <input type="text" class="form-control" name="nama" id="nama"
                                    placeholder="Masukkan Nama">
                                @error('nama')
                                <div class="alert alert-danger">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="umur">Umur</label>
                                <input type="number" class="form-control" name="umur" id="umur"
                                    placeholder="Masukkan Umur">
                                @error('umur')
                                <div class="alert alert-danger">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="bio">Bio</label>
                                <input type="text" class="form-control" name="bio" id="bio" placeholder="Masukkan bio">
                                @error('bio')
                                <div class="alert alert-danger">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/casts.blade.php
@extends('template.layout')

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="content-header">
                <div class="container-fluid">

                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col">

                                    <div class="card mt-5 bg-info ">
                                        <div class="card-body">
                                            <div class="row mb-2">
                                                <div class="col">
                                                    <a href="{{ route('casts.create') }}"
                                                        class="btn btn-md btn-success mb-3">TAMBAH CAST</a>

                                                    <table id="example1" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>Nama</th>
                                                                <th>Umur</th>
                                                                <th>Bio</th>
                                                                <th>Aksi</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                            @forelse ($cast as $casts)
                                                            <tr>
                                                                <td>{{ $casts->nama }}</td>
                                                                <td>{{ $casts->umur }}</td>
                                                                <td>{{ $casts->bio }}</td>
                                                                <td class="text-center">
                                                                    <form
                                                                        onsubmit="return confirm('Apakah Anda Yakin ?');"
                                                                        action="{{ route('casts.destroy', $casts->id) }}"
                                                                        method="POST">
                                                                        <a href="{{ route('casts.edit', $casts->id) }}"
                                                                            class="btn btn-sm btn-primary">EDIT</a>
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="submit"
                                                                            class="btn btn-sm btn-danger">HAPUS</button>
                                                                    </form>
                                                                </td>
                                                            </tr>
                                                            @empty
                                                            <div class="alert alert-danger">
                                                                Data Post belum Tersedia.
                                                            </div>
                                                            @endforelse
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/depan.blade.php
@extends('template.layout')

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="content-header">
                <div class="container-fluid">

                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-sm-6">

                                    <h3>Halaman Home</h3>
                                    <h1> Halaman Toko Online Tamvan </h1>

                                    <p>Bahagia berbelanja bersama kami</p>
                                    <div class="container">
                                        <h1>Keuntungan </h1>

                                        <ul class="list-group">
                                            <li class="list-group-item">1. Murah</li>
                                            <li class="list-group-item">2. Aman</li>
                                            <li class="list-group-item">3. Terpercaya</li>
                                            <li class="list-group-item">4. Luas</li>
                                        </ul>
                                    </div>
                                    <h6>Silahkan klik untuk daftar account ini <a href="/tugas15/public/form"> Form</a></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/edit-cast.blade.php
@extends('template.layout')

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="content-header">
                <div class="container-fluid">

                    <div class="card-body">
                        <form action="/casts/{{ ( $cast->id) }}" method="POST">
                            @csrf
                            @method('PUT')


                            <div class="form-group">
                                <label class="font-weight-bold">Nama</label>
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                    value="{{ old('nama', $cast->nama) }}" placeholder="Masukkan nama cast">

                                @error('nama')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">Umur</label>
                                <input type="number" class="form-control @error('umur') is-invalid @enderror"
                                    name="umur" value="{{ old('umur', $cast->umur) }}" placeholder="Masukkan umur ">

                                @error('umur')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Bio</label>
                                <input type="text" class="form-control @error('bio') is-invalid @enderror" name="bio"
                                    value="{{ old('bio', $cast->bio) }}" placeholder="Masukkan bio ">

                                @error('bio')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>



                            <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/form.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>Halaman Sign In</title>
</head>

<body>
    <div class="container ">
        <h3 class="text-center pb-3 pt-3">Halaman Sign In</h3>
        <div class="card">
            <div class="card-body">
                <form action="/home" method="post">

                    @csrf
                    <div class=" mb-3">
                        <label for="Nama Depan" class="form-label">First Name</label>
                        <input type="text" class="form-control" name="namadepan">
                    </div>
                    <div class="mb-3">
                        <label for="Nama Depan" class="form-label">Last Name</label>
                        <input type="text" class="form-control" name="namabelakang">
                    </div>
                    <div class="form-check">
                        <h4>Gender:</h4>
                        <input class="form-check-input" type="radio" name="gender" id="flexRadioDefault1">
                        <label class="form-check-label" for="flexRadioDefault1">
                            male
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" id="flexRadioDefault2" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Female
                        </label>
                    </div>
                    <select class="form-select mt-3" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="1">Indonesia</option>
                        <option value="2">Malaysia</option>
                        <option value="3">Singapore</option>
                    </select>
                    <div class="form-check pt-3">
                        <h4>Language Speaker</h4>
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            English
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                        <label class="form-check-label" for="flexCheckChecked">
                            Arabic
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                        <label class="form-check-label" for="flexCheckChecked">
                            Dan lain lain
                        </label>
                    </div>

                    <div class="container mt-4">
                        <div class="form-group">
                            <label for="exampleTextarea">Input Bio</label>
                            <textarea name="bio" class="form-control" id="exampleTextarea" rows="3"></textarea>
                        </div>
                    </div>
                    <button type="submit" value="submit" class="btn btn-primary mt-4">Submit</button>
                </form>
            </div>
        </div>

    </div>



</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
</script>

</html>

resources/views/home.blade.php
@extends('template.layout')

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="content-header">
                <div class="container-fluid">

                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col">

                                   <div class="card mt-5 bg-info ">
                                    <div class="card-body">
                                        <h3 class="text-center border-bottom">Selamat Anda Berhasil Daftar</h3>
                                        <h4>Selamat datang {{ $namadepan }} {{ $namabelakang }}</h4>
                                        <h5>Mari Berbelanja Dengan website kami!!!</h5>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection